### PR TITLE
DS 886: Teaser Updates

### PR DESCRIPTION
**Pull request by MarcinMr**
## Jira

https://pegadigitalit.atlassian.net/browse/DS-886

## Summary

The Teaser was updated with two props that can more completely replace the Card Component.

## Details

**1. A `spacing` prop with the following options was added**
- small
- medium
- large

**2. A `border_radius` prop with the following options was added**
- none
- small
- large

**3. A test page was created with all new props options `/pattern-lab/?p=tests-teaser-spacing-and-border-radius`**

## How to test

Pull the branch. Check the test page and confirm that the new props work as expected and the component can more completely replace old Card.

## Release notes

The Teaser component has two new props (`spacing`, `border_radius`) that can be applied to the card variant teaser .

### Visual changes

The spacing and the corner roundness can be adjusted in the card variant teaser component.

### CODE REVIEW

**Comment by cjwhitedev** [comment]
@MarcinMr I'd like to see a demo page as well, something public facing since the test pages are hidden.

**Comment by MarcinMr** [comment]
> @MarcinMr I'd like to see a demo page as well, something public facing since the test pages are hidden.

True:) I'll add a demo example

**Comment by MarcinMr** [comment]
@cjwhitedev updated the docs, it's ready for review again

**Review by cjwhitedev — APPROVED** [review]

**Comment by colbytcook** [comment]
@MarcinMr I think we should adjust the `large` prop value border radius value to `0.37em` to better align with the outer radius. Refer to the adjustments I made in the browser to see the change. Let me know if you have any other questions regarding this.
radius-adjustment

**Review by colbytcook — CHANGES_REQUESTED** [review]
See other comment (I am forced to leave a comment!!)

**Comment by MarcinMr** [comment]
@colbytcook I updated the signifier border-radius to 0.37em

**Review by colbytcook — APPROVED** [review]

**Comment by colbytcook** [comment]
@MarcinMr approved, feel free to merge

**Comment by MarcinMr** [comment]
@colbytcook Merged

**Pull request merged**
