### PR TITLE
DS-141: Remove Unused Dependencies

### PR DESCRIPTION
**Pull request by cjwhitedev**
## Jira

[https://pegadigitalit.atlassian.net/browse/DS-141](https://pegadigitalit.atlassian.net/browse/DS-141)

## Summary

Remove unused dependencies.

## Details

Use [depcheck](https://github.com/depcheck/depcheck) to remove unused dependencies.

## How to test

1. Pull this branch
2. Remove the node_modules folder or otherwise clean your installation
3. Run `yarn setup` and `yarn start` to confirm there are no issues.

### CODE REVIEW

**Review by mikemai2awesome — COMMENTED** [review]
Does `"stylelint": "^13.12.0"` cover everything now? That's why we removed `stylelint-order` and `stylelint-scss`?

**Comment by danielamorse** [comment]
> @cjwhitedev Does `"stylelint": "^13.12.0"` cover everything now? That's why we removed `stylelint-order` and `stylelint-scss`?

@mikemai2awesome, no longer relevant. I backed out these changes.

**Comment by danielamorse** [comment]
@cjwhitedev @colbytcook as we discussed this morning, I updated this PR to only remove a handful of dependencies which were clearly not in use. There are many more that appear to be unused but it's time consuming to verify each one. The are still others that are used but undeclared or declared from an unexpected package.json file. This will be easier to clean up as we port code over to the new repo and consolidate our package.json files.

If this builds successfully on Travis I'd say it's good to merge.

**Comment by danielamorse** [comment]
Failing on Travis but builds fine locally. I believe Travis cache needs to be cleared but the Caches page is down on Travis. I'm going to merge to unblock subsequent PRs.

**Pull request merged**
