### PR TITLE
Allow Blockquote font weight to be customized 

### PR DESCRIPTION
**Pull request by sghoweri**
## Jira
http://vjira2:8080/browse/BDS-2046

## Summary
Adds the ability to optionally configure the Blockquote font weight to be `bold` via the new `weight` prop.
image

## Details
The comps in http://vjira2:8080/browse/BDS-2016 include a version of Blockquote much bolder than what's currently possible. 
> Note: might be worth mentioning that these aren't the 1st comps I've seen recently that have this treatment.

image

## How to test
- Review changes
- Confirm the new `weight` prop works as expected

@mikemai2awesome @danielamorse any thoughts on how we should demo / document this on the  Blockquote page?

### CODE REVIEW

**Comment by mikemai2awesome** [comment]
@sghoweri Document it the same way as the other props such as border, align, etc.

**Comment by sghoweri** [comment]
> @sghoweri Document it the same way as the other props such as border, align, etc.

@mikemai2awesome okie dokie 👍🏼

**Comment by sghoweri** [comment]
> @sghoweri works as expected. Add some docs and this is good to go.

@danielamorse I'll try to squeeze this in first thing this morning -- otherwise this'll have to wait to ship in our next release.

**Comment by sghoweri** [comment]
PR was released with v2.19.0

**Pull request merged**
