### PR TITLE
Add reminder to urlencode() share tool page titles and URLs.

### PR DESCRIPTION
**Pull request by charginghawk**
## Jira

http://vjira2:8080/browse/WWWD-2826

## Summary

Adds reminder to encode URLs to documentation.

### CODE REVIEW

**Comment by sghoweri** [comment]
@charginghawk would it help if we automatically passed all urls passed into the share component through the `urlencode` function internally (ie. inside the component's twig file itself)?

CC @remydenton

**Comment by charginghawk** [comment]
You don't want to run all URLs through urlencode() - there's one exception where it'd break the copy to clipboard functionality. You could theoretically slim down the schema to page title and URL, but it's fine as is right now, and maybe it's better to leave it flexible for what may come.

**Comment by charginghawk** [comment]
Sorry, I wasn't clear - the exception is for copy to clipboard, where you don't want to run the URL through urlencode(). You don't need to because the URL isn't a param on another URL, but also you get escaped characters that you can't actually enter into a address bar in a browser.

On the Drupal side, the URL and page title is run through urlencode() for everything except copy_to_clipboard.

```
/**
 * Implements hook_preprocess_HOOK().
 */
function pega_bolt_share_preprocess_pattern_share(array &$variables) {
  $request = \Drupal::request();
  $route_match = \Drupal::routeMatch();

  // Get the page title for the share tool.
  // @see https://drupal.stackexchange.com/a/193772/44595
  // @see pegawww_theme_preprocess_page()
  $page_title = urlencode(\Drupal::service('title_resolver')->getTitle($request, $route_match->getRouteObject()));

  // We have encode the URL so its params don't get interpreted as mailto's.
  // @see https://stackoverflow.com/questions/1455867
  $share_url = urlencode($request->getUri());

  $share_email_body = t("I saw this on Pega.com and thought you might find it interesting: @url", ['@url' => $share_url]);

  $variables['sources'] = [];
  $variables['sources'][] = ['name' => "facebook", 'url' => "https://www.facebook.com/sharer/sharer.php?u=" . $share_url . "&src=sdkpreparse"];
  $variables['sources'][] = ['name' => "twitter", 'url' => "https://twitter.com/intent/tweet?url=" . $share_url . "&text=" . $page_title . "&via=pega"];
  $variables['sources'][] = ['name' => "linkedin", 'url' => "https://www.linkedin.com/shareArticle?url=" . $share_url . "&title=" . $page_title];
  $variables['sources'][] = ['name' => "email", 'url' => "mailto:?subject=" . $page_title . "&body=" . $share_email_body];
  $variables['copy_to_clipboard'] = ['text_to_copy' => $request->getUri()];

  // Convert attributes to an object if not already.
  if (is_array($variables['attributes'])) {
    $variables['attributes'] = new Attribute($variables['attributes']);
  }
  // All share tools should hide on mobile, where the share tool in
  // page.html.twig appears.
  $variables['attributes']->addClass('u-hide@only-small');
}
```

**Comment by charginghawk** [comment]
A snag to putting it together in the Bolt template is that the $share_email_body uses $share_url in a not-completely-simple way, particularly when you take translation into account.

**Comment by margoromo** [comment]
@charginghawk @christophersmith262 - does this apply now with base theme?

**Comment by margoromo** [comment]
We still need this, this should be a documentation focus.

**Pull request closed without merging**
