### PR TITLE
DS-576 fix static page header dropdown position

### PR DESCRIPTION
**Pull request by mikemai2awesome**
## Jira

https://pegadigitalit.atlassian.net/browse/DS-576

## Summary

Fixes an issue with static page header's top level item dropdown does not move with the page header as the user scrolls.

## Details

1. Updated CSS to use absolute position rather than fixed
2. `flat` prop has been moved from ul template to li template

### How to make a top level item use a single level flat dropdown

```twig
{% set flat_lv2_ul_content %}
  {% include '@bolt-components-page-header/page-header-nav-li.twig' with {
    link: {
      content: 'Flat Level 2',
      attributes: {
        href: 'https://pega.com',
      },
    },
  } only %}
{% endset %}
{% set flat_lv2 %}
  {% include '@bolt-components-page-header/page-header-nav-ul.twig' with {
    content: flat_lv2_ul_content,
  } only %}
{% endset %}

{% include '@bolt-components-page-header/page-header-nav-li.twig' with [
  {
    link: {
      content: 'Why Pega?',
    },
    children: flat_lv2,
    flat: true,
  },
] only %}
```

## How to test

Run the branch locally and check a demo page that has a static page header, hover over each top level items to see the dropdowns. Scroll the page and make sure the dropdowns move with the page header.

http://localhost:3000/pattern-lab/?p=pages-d8-browse-page-media

### CODE REVIEW

**Comment by remydenton** [comment]
Shouldn't we update the schemas to move the `flat` prop from ul to li? https://github.com/boltdesignsystem/bolt/blob/hotfix/ds-576-static-page-header/packages/components/bolt-page-header/page-header-nav-ul.schema.js#L27-L32

**Review by danielamorse — APPROVED** [review]
@mikemai2awesome this works as expected. Thanks for making the CSS work.

I'm approving now since I'll be out tomorrow, but:
1. I have the same question as @remydenton about where the `flat` prop goes
2. Look at the `lerna.json` file on this branch. It says `"version": "3.8.0"`. It should say `3.8.1`, the `release/3.x` branch might need some updates before you merge this for auto-release to work.

**Comment by mikemai2awesome** [comment]
@danielamorse @remydenton I fixed the schemas

**Comment by danielamorse** [comment]
Update: I merged `release/v3.8.x` into `release/3.x`. That should take care of the Lerna issues. Merge when ready!

**Review by remydenton — APPROVED** [review]

**Comment by remydenton** [comment]
@danielamorse, it looks like merging `release/v3.8.x` into `release/3.x` actually kicked off a release of a 8.2 version, which is effectively empty: https://github.com/boltdesignsystem/bolt/releases/tag/v3.8.2.

I'm going to try to resolving the resulting .incache conflicts.   Hopefully this works as planned...

**Pull request merged**
