### PR TITLE
Icon Refactor: Switch To SVG Sprite Loader + SVGO Loader 

### PR DESCRIPTION
**Pull request by sghoweri**
## Jira
N/A

## Summary
Switches Webpack over to use https://github.com/JetBrains/svg-sprite-loader + optimize SVGs via SVGO. Subset of the work from #1602.

This replaces the vast majority of the custom code originally written for Bolt's custom Icon build process + switches us over to using a process which has more clearly defined (and mostly off the shelf) Webpack loaders that each handle one thing at a time.

Furthermore, SVG Sprite Loader supports Webpack DLLs out of the box so this shouldn't have any gotchas integrating with Base Theme. 🎉 

## Details
- This PR also adds the `@bolt-assets` Twig namespace to the ones automatically registered with Twig internally -- already in use in Bolt for a long, long time -- since this namespace helps provide a predictable way to resolve Bolt-build files within Twig templates. Used for adding Twig-based SSR support to Icons.
- WIthout the two custom Webpack loaders from #1614, the build here can't fully run
- Even with these loaders, without modifications to the Icon component itself (separate PR), the generated SVG spritesheet wouldn't get used by the original version of Icon.

### CODE REVIEW

**Comment by sghoweri** [comment]
> @sghoweri should this point to a 3.x branch or is this going in 2.x?
> 
> We'll need a version of this that is testable to really review it. Are you planning to make a PR that assembles these PRs?

@danielamorse We need this on v2.x since Academy uses these new Icon options in a number of places.

 I do already have these PRs fully assembled here for reference! https://github.com/boltdesignsystem/bolt/pull/1602

**Comment by danielamorse** [comment]
> > @sghoweri should this point to a 3.x branch or is this going in 2.x?
> > We'll need a version of this that is testable to really review it. Are you planning to make a PR that assembles these PRs?
> 
> @danielamorse We need this on v2.x since Academy uses these new Icon options in a number of places.
> 
> I do already have these PRs fully assembled here for reference! #1602

Ok, you can add me as a reviewer to #1602 if you want me to take a look @sghoweri

**Comment by sghoweri** [comment]
👍🏼

**Comment by sghoweri** [comment]
PR was released with v2.16.0

**Pull request merged**
