### PR TITLE
Border Radius | FE | Convert components to use border radius function

### PR DESCRIPTION
**Pull request by mikemai2awesome**
## Jira

http://vjira2:8080/browse/BDS-1156

## Summary

Updated component specific CSS to use the new border-radius function.

## Details

Many components' CSS got updated, such as the following:

* blockquote
* button
* card
* chip
* code snippet
* form
* icon
* nav-priority
* navlink
* pagination
* tooltip
* video

## How to test

Run the branch locally and checked the demo pages for the list of affected components. Make sure the border radius is displaying correctly.

### CODE REVIEW

**Comment by mikemai2awesome** [comment]
@adamszalapski I agree!

But I refrained myself from dealing with commented code, and only stick to the task of updating border radius.

**Comment by mikemai2awesome** [comment]
@danielamorse Thanks for catching that. Those 2 components need to be refactored, they are using raw HTML with component classes. 😞 

Added the class now.

**Comment by mikemai2awesome** [comment]
@sghoweri 

Before we merge this to master, I need to manually resolve all the conflicts. Github is not good at merging this because this PR is old.

**Comment by mikemai2awesome** [comment]
@sghoweri @danielamorse 

Conflicts have been sorted.

**Comment by colbytcook** [comment]
Work being tracked in https://pegadigitalit.atlassian.net/browse/DS-109

**Pull request closed without merging**
