### PR TITLE
Epic - Typeahead: CSS Modules

### PR DESCRIPTION
**Pull request by sghoweri**
## Jira
http://vjira2:8080/browse/BDS-1807

## Summary
Adds CSS Module support to the Build Tools. These updates allow for auto-generated scoped CSS selectors to keep templates, styles and JS all in sync. 

Part of the broader [Typeahead](#1311) component work.

## Details
- Adds opt-in support for [CSS Modules](https://css-tricks.com/css-modules-part-1-need/) to the existing Build process. 
- Only components with Sass files named `NAME.scoped.scss` have their class names semi-randomly generated when compiling. 
- The way these build updates are set up, the Sass file ending in `.scoped.scss` is what triggers the JSON file with the key:value pairs to get generated and added to the folder the Sass file is living in. This is the critical piece in how the class names that get used in the Twig template stay in sync with the CSS getting compiled.
- Javascript files pulling in `.scoped.scss` files also trigger this "opt-in" CSS Module behavior, however these use a different mechanism under the hood to generate the generated class names. Essentially we're using two different off the shelf approaches to handling CSS Modules that both share the same "randomly generated class name" selector logic.

## How to test
- Review PR changes
- Confirm Travis build passing as expected
- Check out the full Typeahead code branch to see how these changes actually fit into the current workflow + build process:
  - [typeahead.scoped.json](https://github.com/bolt-design-system/bolt/blob/feature/typeahead/packages/components/bolt-typeahead/typeahead.scoped.json)
  - [typeahead.scoped.scss](https://github.com/bolt-design-system/bolt/blob/feature/typeahead/packages/components/bolt-typeahead/typeahead.scoped.scss) (nothing different other than the `.scoped.scss` file name)
  - [typeahead.twig](https://github.com/bolt-design-system/bolt/blob/feature/typeahead/packages/components/bolt-typeahead/typeahead.twig#L1) -- pulls in the external (dynamically generated but still committed to Git) JSON file to map to the compiled CSS class names / selectors
  - [typeahead.js](https://github.com/bolt-design-system/bolt/blob/feature/typeahead/packages/components/bolt-typeahead/typeahead.js#L10) - which pulls in the scoped Sass file + maps to a modified version of the classnames helper library to match to selectors [like this](https://github.com/bolt-design-system/bolt/blob/feature/typeahead/packages/components/bolt-typeahead/typeahead.js#L104) automatically

### CODE REVIEW

**Comment by sghoweri** [comment]
@christophersmith262 and @danielamorse any feedback on this before we merge this in for the upcoming v2.9.0 release?

**Comment by sghoweri** [comment]
> @sghoweri thanks for the clear PR description. I get it now, and it looks like you did a nice job setting up scoped selectors in Bolt!
> 
> Couple things before I finish the review:
> 
> * There are conflicts with Master that need to be resolved.
> * When I inspect the Typeahead component I don't see any CSS associated with elements using the scoped classnames (see [staging](https://boltdesignsystem-c97n5oj1k.now.sh/pattern-lab/?p=components-typeahead--dynamically-fetch-data)). They're just using vanilla form styles. Is it not working or is it supposed to be unstyled?
> * Twig (no-JS) version has styles but no scoped classnames. Isn't Twig supposed to use the scoped classnames, too?

@danielamorse I'll need to resolve those merge conflicts but regarding the Twig-specific selectors for Typeahead, I just needed to enable the feature flag I had set up for this 😉 

https://github.com/boltdesignsystem/bolt/commit/2ea655be1d9e92ddbd3c35764141b639eca853a2

**Comment by danielamorse** [comment]
> I just needed to enable the feature flag I had set up for this 😉

Hmm, still not working for me. Any ideas?
image

**Comment by sghoweri** [comment]
> > I just needed to enable the feature flag I had set up for this 😉
> 
> Hmm, still not working for me. Any ideas?
> image

@danielamorse fixed it! Had to tweak the Webpack logic after all the merging + update the Typeahead Nightwatch test to account for the semi-mangled classnames that are getting used here. 

Should be good to take another look at :)

**Comment by danielamorse** [comment]
@sghoweri I looked again and the Typeahead styles still aren't working. No JS errors. Try again? Or, let me know if you're seeing something different locally.

**Comment by danielamorse** [comment]
@colbytcook closing, this is neat but at the moment we're not looking to implement randomly generated class names. I won't delete the work, just closing the PR.

**Pull request closed without merging**
