### PR TITLE
DS-590 page header + notifications design

### PR DESCRIPTION
**Pull request by mikemai2awesome**
## Jira

https://pegadigitalit.atlassian.net/browse/DS-590

## Summary

Adds user notifications to Page Header component.

## Details

1. Related-sites nav and user nav are breaking changes. New data needs to be passed to create the new design.
2. Page Header's nav-li template has new props: `counter`, `signifier_only`, `signifier_before`.
3. Minor letter spacing tweak to xsmall headlines.
4. Updated Page Header docs.

## How to test

Run the branch locally and check all the demos under Page Header.

### CODE REVIEW

**Review by danielamorse — CHANGES_REQUESTED** [review]
@mikemai2awesome in the [logged-in demo](https://feature-ds-590-page-header-notifications.boltdesignsystem.com/pattern-lab/?p=components-page-header-example-main-site-with-subnav) the Notifications menu is inside a `<div>` directly inside a `<ul>`. We're missing the `<li>`.

When I add the missing wrapper template (`@bolt-components-page-header/page-header-nav-li.twig`), I see extra padding around the Notifications content that wasn't there before.

Can you take a look at this? Let me know if you want me to push my docs-site edits.

**Comment by mikemai2awesome** [comment]
@danielamorse I just fixed it.

**Review by danielamorse — APPROVED** [review]

**Comment by remydenton** [comment]
I don't quite understand how the old content maps to the new.  Specifically, how does this

Screen Shot 2022-01-18 at 5 11 05 PM

Become this?

Screen Shot 2022-01-18 at 5 11 13 PM

**Review by remydenton — APPROVED** [review]
Approved!  As discussed in standup, the answer to my previous question is that the content changes significantly.  The plan is to hard-code those links so that they can be easily synchronized across sites.

**Pull request merged**
