### PR TITLE
Fix issues with checkboxes on Safari browser

### PR DESCRIPTION
**Pull request by adamszalapski**
## Jira

https://pegadigitalit.atlassian.net/browse/DS-422

## Summary

Fix visual issues on input on Safari.

## Details

Updating the input `z-index` css styles.

## How to test

1. Open Safari browser
2. Go to https://boltdesignsystem.com/pattern-lab/patterns/40-components-form-35-form-element-demo-checkbox-fieldset/40-components-form-35-form-element-demo-checkbox-fieldset.html
3. Check if you can reproduce the issue mentioned in https://pegadigitalit.atlassian.net/browse/PP-244
4. Go to https://bugfix-ds-422-safari-search-facet-texts-n.boltdesignsystem.com/pattern-lab/patterns/40-components-form-35-form-element-demo-checkbox-fieldset/40-components-form-35-form-element-demo-checkbox-fieldset.html
5. Check if the issue still exists, if not we are good to go.

### CODE REVIEW

**Comment by colbytcook** [comment]
@adamszalapski I am still not able to reproduce the original bug, I am not sure why. @mikemai2awesome are you able to see the behavior reported on PP-244?

**Comment by mikemai2awesome** [comment]
@adamszalapski @colbytcook No, I cannot reproduce this neither. I can't debug it but this change is good regardless, we don't need to set `z-index`.

**Review by mikemai2awesome — APPROVED** [review]

**Comment by krlucas** [comment]
@adamszalapski I was able to reproduce the issue with the link in step 2, but with the link in step 4. 
Safari Version 14.0.3 (15610.4.3.1.7, 15610)

Looks like the fix worked.

**Comment by adamszalapski** [comment]
Thank you @krlucas for testing and confirmation.

**Pull request merged**
