### PR TITLE
fix/remove empty slots on remove

### PR DESCRIPTION
**Pull request by glassdimly**
## Jira

https://app.asana.com/0/1126340469288208/1154819220959429

## Summary

Remove empty parent `bolt-animate`s and `slot`s on component remove.

## Details

Empty `slot`s and `bolt-animate`s were causing layout problems in the `bolt-two-character-layout`.

Previously, empty `bolt-animate`s were removed on save, but this was [removed](https://github.com/boltdesignsystem/bolt/commit/37de97f3b6fb06cfab0fdb5fffdd97c9c9ccc5d8#diff-35c3dd77f021c1aefdc961b00bfce436L226). We can't add it back in there because the way we're getting and setting html to save is different and putting it there would be a hack. So, whenever a component is removed, I check if the direct parent is a `bolt-animate`. If so, it's empty, and I remove it. I also see if it is a `slot`, and remove that slot as well.

## How to test
Edit content. Remove content from `bolt-character`'s slots without actually removing the parent animate, especially the right and left slots. Save, and content will look fine, not off-center.

### CODE REVIEW

**Comment by glassdimly** [comment]
Let's connect by voice about this. I want to understand better what you meant when you said 

> as it is now, testers have to re-create any test content that has empty animate components or slots-- it's both more work and makes it harder to test that it fixes the problem

I want to make sure we get a solution that works for everyone here.

I also want to be clear that re-instituting the the on-save event wasn't an option without converting the output string to traversible DOM content and traversing it for empty slots, which would be a hack. Before, we were traversing the `container` (the DOM content in the broswer) after save, which is no longer an option because the DOM string content handed over to Drupal is generated before `container` DOM content is outputted there.

**Comment by sghoweri** [comment]
@remydenton @margoromo which version of Bolt do we want this to ship with? v2.14.1 or v2.15.0?

**Comment by margoromo** [comment]
> @remydenton @margoromo which version of Bolt do we want this to ship with? v2.14.1 or v2.15.0?

I would defer to @remydenton - but my inclination is v2.14.1

**Comment by remydenton** [comment]
Yep, I think this is probably `hotfix` material @sghoweri.  While there is other Micro journey work in progress, this PR affects the editor component so it can't be tested in Drupal until it's released with Bolt.

**Comment by remydenton** [comment]
Closing in favor of #1676, which is a rebased version to release as a hotfix.

**Pull request closed without merging**
