### PR TITLE
SVG Icon Refactor: Simpler Build Process, More Easily Add Custom Icons, New Color & Background Options

### PR DESCRIPTION
**Pull request by sghoweri**
## Jira
- http://vconfluence2:8080/display/PEGAKIT/Academy+Design+UI#AcademyDesignUI-Icon

<h2 id="summary">Summary</h2>

Several major updates to the Icon component + Icon-related build process to more easily support adding custom SVG icons + address gaps like background shape support + built-in color options! 

- On 4G: Icons display [~2.5 seconds faster](https://www.webpagetest.org/video/compare.php?tests=191210_RS_e32aee83e1b62692810ef5b233800548%2C191210_K9_a4970e8522777ea8fdd9630e74b59b3c&thumbSize=200&ival=100&end=visual)
- On 3G (Slow) icons display [~4 seconds faster](https://www.webpagetest.org/video/compare.php?tests=191210_0X_333bf2c2f8ce26128eb0aa4f41634234,191210_13_a0dcab87a7d351ccbb18516da2945c07)
- On Desktop Icons display [~1s faster](https://www.webpagetest.org/video/compare.php?tests=191210_QS_1dc3699d53b28aed972c94ebab85bab9%2C191210_ZN_5909fde36b5e706956fd3bf205d03b71&thumbSize=200&ival=100&end=full)

# Required PRs:
- [x] Removing Pre-compiled SVGs from the repo via #1611 
- [x] Manually rename / fix mask in a few SVGs via #1608
- [x] Update component Jest test snapshots via #1612 
- [x] Docs / Demo updates via #1610 
- [x] Customized Webpack Loaders via #1614
- [x] Updates to the Icon build process #1615
- [x] Icon component-specific updates via #1617

<hr>

## Details
- Majority of the SVG icon build process is now using off the shelf Webpack code!
- Zero .boltrc config required
- Pre-compiling step no longer used — just run the Webpack build!
- The `background` prop (the background shape appearing behind / around the SVG icon) now works with icons of all sizes — no longer limited to just `xlarge` icons!
- The `background` prop now includes a new `outline` option to account for icon variations with a stroke around the main icon shape
- 1st gen SSR support for SVG icons (via inline Twig include of the minified SVG) is now supported.
- SVG files imported into JS files are now automatically turned into icons
    - SVGs imported into other files (ex. .scss files) are handled normally
- All SVGs referenced in JS and SCSS files are now automatically minified￼
- No longer need to have a separate build task for aggregating SVG icons (now that we are using require.context internally)
- SVG icons have switched from using the actual inline SVG markup to now be using symbols
- No longer need to commit pre-compiled icons to the repo + no longer need to write to the component folder while compiling
- The `color` prop has been expanded to include support for the most common custom color variations used:
    - blue
    - orange
    - yellow
    - gray
    - green
    - teal
    - pink
    - indigo

88D45821-2AEF-4A71-B4E6-84A9BFFF6E84

# How It Works:
- Vanilla `svgo-loader` to optimize SVG size
- Custom fork of `svg-transform-loader` to add custom regex to find and replace certain colors
- Vanilla `svg-sprite-loader` with config to handle runtime generator + custom SVG icon template

```
// index.js

import ‘./customer-support.svg`;

// Now you can use it:
// <bolt-icon name=“customer-support”></bolt-icon>
//

import ‘./triangle-right-colored.svg`;

// Now you can use it:
// <bolt-icon name=“triangle-right-colored”></bolt-icon>
//
```

# Caveats:
- In order to add “proper” background shape support and address previous SVG icon issues, the SVG sizes for `large` and `xlarge` are now different. This _might_ require some existing SVG icon instances to get updated to use the larger SVG icon size if desired.
- The iconDir option for the .boltrc config has been disabled since its not being used by the base theme. #useItOrLoseIt
- We are no longer “magically” fixing file name issues. 
    - Internal icons shipping in Bolt have been manually renamed. External custom SVG icons must not contain spaces, underscores, or dots — only dashes!
- “Colored” SVG icons — those that retain all original stroke and fill colors — must have a filename that end with “-colored.svg” — all others will automatically have their colors stripped out and replaced in order for the color theming system to work properly.
- “Holes” In Filled Icons: SVG icons (filled icons) that visually have a shape or color punched out must be manually cropped / cut out. “Magical” workarounds for IE 11 support are no longer supported so manually cutting out the shape that “appears” to be cut out is strongly recommended.

## How to test
- [ ] Review updated docs to make sure it makes the instructions on adding custom icons make sense
- [ ] Quick cross-browser sanity check (ex. icon colors still working in IE 11)
- [ ] Confirm SSR icons working as expected when JS is disabled. Note: while doing local development you probably won't see this unless you recompile Twig (or double-check in Prod mode)

Feel free to reference any of the standalone PR's mentioned above if there's anything specific you wanted to check out in isolation!

### CODE REVIEW

**Comment by sghoweri** [comment]
> @sghoweri when you get a chance, would you please resolve the conflicts with master and add testing steps? I get the general idea, but testing steps would be very helpful here. Thank you!

@danielamorse will do!

**Comment by sghoweri** [comment]
@danielamorse I'm gonna add a couple notes on testing / what to look for but other than that this should be ready to take another look at

**Comment by sghoweri** [comment]
> For the most part this is looking really good and almost ready to go. Server-side rendered fonts are a nice improvement. I made a few minor copy edits and formatting fixes to the docs ([see commit](https://github.com/boltdesignsystem/bolt/pull/1602/commits/b167f9db68de94f50d9f71615b89161f3d6086ba)).
> 
> 1. In IE11 there is a layout issue on the [Color Variation](https://feature-auto-add-icons.boltdesignsystem.com/pattern-lab/?p=components-icon-color-variation) page. Also note the arrows in the navigation are all wrapping. The latter issue is also happening on master so it's not a blocker, but should be fixed at some point.
>    image
> 2. Custom Colors appear different in IE11:
>    image
> 
> Compared to Chrome:
> image

Hey @Dan Morse keep in mind that this is actually a feature (progressively enhanced custom Icon colors without requiring a build step), not a bug since that's currently the exact same intended behavior that happens with the current version of Icons out in the wild.

That said, the updates here should allow for built in Icon colors to work in IE 11, yes?

**Comment by sghoweri** [comment]
@danielamorse regarding your other comment - my preference would be to ideally get this batch of updates merged down to master to avoid having to do a bunch of rework (if we keep sitting on this) and then we get a quick follow-up fix for that Icon demo before we cut the next Bolt release. 

Your call!

**Comment by danielamorse** [comment]
@sghoweri oddly, when I build locally the IE11 bug I reported goes away. Yet, I was seeing it on now.sh. 🤷‍♂ 

I'm going to approve this since it's a very minor IE11-only PL bug. Let's check again once everything is merged down.

**Comment by danielamorse** [comment]
@sghoweri do these changes require any updates for consumers of Bolt? I'm thinking specifically of the build tools in Base Theme.

**Comment by sghoweri** [comment]
> @sghoweri do these changes require any updates for consumers of Bolt? I'm thinking specifically of the build tools in Base Theme.

Since this is shifting everything over to compile SVG icons through Webpack, no tooling specific updates should be required downstream. All custom icons in use have been handled via Bolt releases as far as I know (ex. Micro Journey icons, Collaboration Center icons, Academy icons).

This update should actually make it even easier to use custom icons downstream without requiring a Bolt release since all that's now required is to import an SVG file from JS compiled by Webpack... that's it!

**Comment by sghoweri** [comment]
PR was released with v2.16.0

**Pull request merged**
