### PR TITLE
Remove `@bolt/polyfill` workaround from `@bolt/element`

### PR DESCRIPTION
**Pull request by sghoweri**
## Jira
http://vjira2:8080/browse/BDS-2112

## Summary
Removes the temporary polyfill package added to `@bolt/element` as part of the overall batch of bundle size / execution time-related performance improvements.

The goal here is to have the main / initial JS file that gets downloaded be as small as possible so async loaded components load up ASAP.

## How to test
@remydenton any thoughts on how we can test this update out before releasing?

### CODE REVIEW

**Comment by sghoweri** [comment]
@remydenton I'm assigning this to you as the primary reviewer but including @danielamorse as well for a 2nd set of eyes on this (seemingly) tiny update.

**Comment by remydenton** [comment]
@sghoweri, my memory was jogged on this by some updates Marcin was making to micro journeys (https://gitlab.com/pegadigital/pegawww/pegawwwd8/-/merge_requests/151).  If I'm remembering correctly, adding that `import '@bolt/polyfills';` line resolved a problem with dependencies for components in the Drupal theme (e.g. micro journeys and WWO) that were relying on Bolt components.

I'm all for removing it if those polyfills are no longer required based on our supported browsers.  But we should do so only after polyfills have been removed those components, e.g. [here](https://github.com/boltdesignsystem/bolt/blob/master/packages/experimental/micro-journeys/index.js).

**Comment by sghoweri** [comment]
> @sghoweri, my memory was jogged on this by some updates Marcin was making to micro journeys (https://gitlab.com/pegadigital/pegawww/pegawwwd8/-/merge_requests/151). If I'm remembering correctly, adding that `import '@bolt/polyfills';` line resolved a problem with dependencies for components in the Drupal theme (e.g. micro journeys and WWO) that were relying on Bolt components.
> 
> I'm all for removing it if those polyfills are no longer required based on our supported browsers. But we should do so only after polyfills have been removed those components, e.g. [here](https://github.com/boltdesignsystem/bolt/blob/master/packages/experimental/micro-journeys/index.js).

@remydenton which, FWIW, is already happening ([here](https://github.com/boltdesignsystem/bolt/blob/feature/globally-use-lazy-queue/packages/experimental/micro-journeys/main.js)  and [here](https://github.com/boltdesignsystem/bolt/blob/feature/globally-use-lazy-queue/packages/experimental/micro-journeys/index.js).

**Comment by remydenton** [comment]
So how come I had to be the one to dig that up?  Previously, we had an integration problem and you added a workaround for the problem.  Then months later, you remove the workaround for performance reasons without a discussion or acknowledgment of what the original problem was, much less instructions for how to pull this in without breaking things.

It feels like you're taking one of these stances:
* "I'm probably breaking that thing I fixed, but I don't really remember what it was.  I'll wait for someone else to find it if it's still a problem"
* "I know exactly what this breaks, but I'm not going to mention it in PR description"

Am I misunderstanding?  Just trying to understand where your thinking is on this one.

**Comment by danielamorse** [comment]
@remydenton I'm going to merge this into `v3.0-rc.2`. This is the release candidate with the riskier code changes in it.

I don't think we can remove `@bolt/polyfills` here without adding it downstream. `@bolt/polyfills` is added by the Bolt build tools automatically [here](https://github.com/boltdesignsystem/bolt/blob/master/packages/build-tools/create-webpack-config.js#L75-L92), but base theme uses an earlier version of the build tools that does not add it.

When the time is right, I suggest we upgrade the build tools in Base theme. For now, we could settle for just including `@bolt/polyfills` in the Base theme build (exactly how we do that tbd).

**Review by danielamorse — APPROVED** [review]
Approved to merge into `v3.0-rc.2`

**Comment by remydenton** [comment]
@danielamorse, pega.com updates the build tools to v2.25.1 with [a patch](https://gitlab.com/pegadigital/pegawww/pegawwwd8/-/blob/release/release-77/patches/WWWD-4600-update-bolt-build-tools-to-v2.25.patch).  I'm not clear why it's a patch (meaning only pega.com gets it-- @charginghawk or @relimck may know more), but at least it's proof that a recent enough version of the build tools to avoid this problem can be used.  Specifically, it looks like 2.25 has the line you mention:  https://github.com/boltdesignsystem/bolt/blob/v2.25.1/packages/build-tools/create-webpack-config.js

**Comment by danielamorse** [comment]
Good point @remydenton, so the polyfills _are_ being loaded via the Base theme build tools on pega.com. I still don't understand why the polyfills are not there when the base theme component JS runs (recall [web-component-workaround](https://gitlab.com/pegadigital/bolt/pega_bolt_theme/-/blob/8.x-2.x/packages/components/components-web-component-workaround/src/web-component-workaround.js#L1)), but maybe that's a separate issue. I may want to troubleshoot that particular issue some more.

We'll have to upgrade the build tools (or patch them) in order to drop IE11 support in the Base theme itself. Perhaps we can tackle that after the `v3.0` upgrade is rolled out.

**Comment by danielamorse** [comment]
Note: I accidentally overwrote the merge into `feature/v3.0-rc.2`. So, I just cherry-picked the original commit and re-added to `feature/v3.0-rc.2`: https://github.com/boltdesignsystem/bolt/commit/e082868e2c731e40a746a3a25e78ca7ed66156ec

**Pull request merged**
