### PR TITLE
BDS | Docs | Typography and spacing

### PR DESCRIPTION
**Pull request by mikemai2awesome**
## Jira

http://vjira2:8080/browse/BDS-2018
http://vjira2:8080/browse/BDS-2019

## Summary

Introduces new versions of documentation for Typography and Spacing.

## Details

1. The docs are rewritten to be more intuitive. Clear values are shown to clarify the current systems.
2. The pages are not completely dynamic yet. I need json data to make them so. This isn't urgent, we'll do it as a fast-follow. @sghoweri 

## How to test

Run the branch locally and proof read Typography and Spacing under Visual Styles.

### CODE REVIEW

**Comment by sghoweri** [comment]
Also question @mikemai2awesome, do we already have a follow-up ticket added somewhere so we get around to updating these to stay automatically up to date? #maintainItOrLoseIt

**Comment by mikemai2awesome** [comment]
@danielamorse @sghoweri 

There are a few reasons I am using straight up web components in recent docs:

1. To separate the twig templates from Doc Site UI, make twig code easier to find.
2. To showcase the actual usage of Bolt, which can be implemented with anything, not just Drupal.
3. To create docs much faster. There's just not enough time for us to document things, they always get de-prioritized. Even though these docs are super useful, no stakeholders asked for them, I just squeezed them in with whatever time I have.

Yes, I am aware of FOUC. That's a good reason for us to push for SSR, that's another thing we don't have dedicated time for.

Follow-up ticket to make the values in the docs dynamic: http://vjira2:8080/browse/BDS-2044

**Comment by sghoweri** [comment]
> @mikemai2awesome much improved 👍
> 
> Copy and visuals are very clear.
> 
> @sghoweri re: using web component only, maybe it's an opportunity to try out some sort of skeleton screen? 💀 🤔
> 
> It's SO convenient that I'm willing to live with the FOUC personally. But I see where you're coming from.

Just trying to practice what I preach about progressive enhancement and perceived performance 🙂

**Comment by sghoweri** [comment]
PR was released with v2.19.0

**Pull request merged**
