### PR TITLE
DS-324 Quick filters

### PR DESCRIPTION
**Pull request by danielamorse**
## Jira

https://pegadigitalit.atlassian.net/browse/DS-324

## Summary

Add Best of Content "Quick Filters" template for WWW team.

## Details

Quick filters is built with "www-" classnames as it will be copied out of Bolt into WWW codebase. It consists of [HTML](https://github.com/boltdesignsystem/bolt/pull/2118/files#diff-b8bdd147ecd94aeec60b8564eddc320d8aba504b98700bf126e66cf44a808e08) and [SCSS](https://github.com/boltdesignsystem/bolt/pull/2118/files?file-filters%5B%5D=.js&file-filters%5B%5D=.scss#diff-cf3f6c17bc43c3115e25202eddb4cb54b957770e8c25cd8d0a11b0faeac238e9).

This PR also adds a new shorthand for triggering a modal, the `data-bolt-modal-target=""` attribute. The value of this attribute is a CSS selector to match the desired modal.

## How to test
- Review the code
- View [demo](https://feature-ds-324-boc-quick-filters.boltdesignsystem.com/pattern-lab/patterns/50-pages-65-best-of-content-13-gallery-phase1/50-pages-65-best-of-content-13-gallery-phase1.html)
- Be sure to test at smaller screen sizes

### CODE REVIEW

**Review by mikemai2awesome — APPROVED** [review]
@danielamorse The styles are good now. Need to wait for Thomas about the HTML.

**Comment by danielamorse** [comment]
@mikemai2awesome this looks great. I like how you handled the focus + selected state 👌 

There's one weirdness I caught: go to small screen and select a quick filter. For me, the filters disappear. I managed to fix it in the inspector by adding `position: relative;` to `.c-www-quick-filters__list-item`. Does this make sense to you why that'd happen?

**Comment by mikemai2awesome** [comment]
@danielamorse Good catch, it's some weird glitch with flex. I put relative on the list container instead. It should be good now.

**Comment by danielamorse** [comment]
@mikemai2awesome re-tested and it's good now 👍

**Pull request merged**
