### PR TITLE
Keep Drupal Lab Dependencies in Sync + Deploy As Static Site

### PR DESCRIPTION
**Pull request by adamszalapski**
## Jira

http://vjira2:8080/browse/BDS-1107

## Summary

Create a static version of Drupal Lab and deploy it with our Bolt Design System website.

## Details
Add Tome module to Drupal-lab.
Update Drupal-lab configuration.
Update Tome configuration.
Add NOW.sh routes.
Update Travis configuration.

## How to test
Run this code locally.

### Test steps
- Run `yarn run clean` command on the root folder
- Now run `yarn run setup`
- Go to Drupal-lab folder using command `cd example-integrations/drupal-lab`
- Then run `yarn run generate` to generate Drupal-lab and static version of drupal-lab
- Go back to root folder using `cd ../../` command
- Run `yarn run build`
- Right now run `yarn run serve` to serve bolt
- Go to the provided link in terminal: ` http://localhost:3123`
- Check if website working as expected
- Go to subpage `http://localhost:3123/drupal-lab` to confirm that Drupal-lab website is working (login functionality is not working because is static version)
- Close connection by using `Control+C`

### Develop test
- Run `yarn start` to run docs-site
- Check if development env work correctly

### Travis check
- Go to this [link](https://bugfix-drupal-lab-integration-issues.boltdesignsystem.com/drupal-lab) to check if Drupal-lab static version is correct on Travis build.

### CODE REVIEW

**Comment by adamszalapski** [comment]
Thanks @remydenton for that deep analyze. We want to fill Drupal Lab with content and components but we don't spoke about it. It's a good idea.

**Comment by sghoweri** [comment]
@adamszalapski could you fix the merge conflict here + take a look why the Travis build was marked as failing? I’d love to merge this down to master!

**Comment by sghoweri** [comment]
> I ran through the testing steps and the static site generation works as expected. I hadn't heard of Tome before--pretty cool!
> 
> A few notes:
> 
> * I updated the Jira issue number in the PR description to the one I think you meant.
> * The idea of using a static site is an interesting one.  On the one hand, we won't be able to try out (and run tests against) things like the authoring experience.  I'm also curious to see just how much of the webform experience Tome can replicate.  On the other hand, it's a simpler and easier way to get a Drupal demo up and running than a full container, and it may allow us to do 80% or more of the tests we care about anyway, in which case it's a great call.
> * Have you and/or @sghoweri already thought about plans for creating default content within Drupal Lab?  It seems like it would be useful with or without Tome, but _especially_ with it--as it is now, there's not much to see on the static site:
>   Screen Shot 2019-08-30 at 4 10 30 PM . If not, I'm happy to help brainstorm on that, as well as the whole setup and where we see it going in the future.

Let's all chat about this and brainstorm some ideas on where we want to take this.

At the moment I'm just happy that we have a new way to test to confirm Drupal integration continues to work as expected _and_ not require Docker containers / a whole new hosting provider to get us there. 

I really wouldn't be opposed to figuring out a path forward to also incorporate authoring + recommended UI for authors, etc (perhaps with a separately deployed instance?) but don't want that to stop us from getting some immediate benefits from this.

Thanks again to everyone for all your help with this + chipping away at getting this finally shipped! 👏😭

**Comment by sghoweri** [comment]
PR was released with v2.13.0

**Pull request merged**
