### PR TITLE
List | FE | Add justify alignment and nowrap prop, plus allow text-wrap inside flex list

### PR DESCRIPTION
**Pull request by mikemai2awesome**
## Jira

http://vjira2:8080/browse/BDS-1902

## Summary

* Fixes a bug where flex list did not allow its items' text content to wrap to a second line.
* Adds `justify` as an option for `align`.
* Adds `nowrap` as a prop.

## Details

1. Flex items are changed to use `flex: 1`, so when a long paragraph of text is passed to each item, the text will wrap to a second line.
2. The new `justify` option under `align` will allow inline and flex items to spread out. Best suited for putting an item on the left and an item on the right.
3. The new `nowrap` prop will prevent inline and flex list items from wrapping to a second line.

## How to test

Pull down the branch locally and perform the following.

### Check tests

- [ ] 1. Given I have pulled down the branch locally
- [ ] 2. And I am in the root folder
- [ ] 3. When I run the command `npx jest packages/components/bolt-list/__tests__/list.js`
- [ ] 4. Then I should see all tests indicated as "Pass"

### Check justify alignment

- [ ] 1. Given I am viewing the align variations page
- [ ] 2. And I am viewing the `Horizontally align inline items: justify` section or the `Horizontally align flex items: justify`
- [ ] 3. Then I should see the items in each list are spaced evenly based on the width of the viewport

### Check nowrap prop

- [ ] 1. Given I am viewing the nowrap variations page
- [ ] 2. And I am adjusting the viewport of the browser
- [ ] 3. Then I should see the items in each list not wrapping to a second line regardless of the viewport size

### CODE REVIEW

**Comment by adamszalapski** [comment]
Please remove lint issue to pass the tests https://travis-ci.com/boltdesignsystem/bolt/jobs/264223334#L623

**Comment by mikemai2awesome** [comment]
@adamszalapski 💥 whoa, good catch. I didn't make those changes... I am gonna revert the merge from master...

**Comment by mikemai2awesome** [comment]
@adamszalapski All set. Got it sorted out. Should only be 7 file changes.

**Comment by sghoweri** [comment]
PR was released with v2.14.0

**Pull request merged**
