### PR TITLE
ci: setup initial GitHub actions

### PR DESCRIPTION
**Pull request by EvanLovely**
## Summary

Adding some initial GitHub actions setup that is pretty awesome and probably the next best CI setup; here's a peak at the initial parts of what Travis CI is doing (but not totally fleshed out). Just the beginning parts that show neat tricks and nice parallelism.

## Details

- [GitHub Actions docs](https://developer.github.com/actions)

## How to test

- Click the "Actions" tab
- 😳

### CODE REVIEW

**Comment by sghoweri** [comment]
🤯

**Comment by sghoweri** [comment]
@EvanLovely got the first couple bits of this working 🎉 

https://github.com/bolt-design-system/bolt/pull/1116/checks?check_run_id=79647452

**Comment by EvanLovely** [comment]
🎉

**Comment by colbytcook** [comment]
Closing because PR is outdated

**Pull request closed without merging**
