### PR TITLE
fix(editor): rearrange step w content

### PR DESCRIPTION
**Pull request by EvanLovely**
## Tasks

- Asana: [Move up/down buttons breaks when applied to pathway steps](https://app.asana.com/0/1126340469288208/1160381693199881/f)
- JIRA: [WWWD-4544](http://vjira2:8080/browse/WWWD-4544)

## Summary

Fixes Editor re-arrangement of Micro Journey Steps

## Details

(Explain the changes in enough detail fo reviewers to understand.  Raise any questions for reviewers to consider.)

## How to test

- Go to https://boltdesignsystem.com/pattern-lab/?p=experiments-micro-journeys and click 'Edit'
- Select one of the `bolt-interactive-step` elements in the layers palette
- Click the `move up` or `move down` button in the editor

**Resolved**: After doing this, the contents of the step you moved will be gone (and won't come back after saving).

# WIP Remaining

- [x] Fix core bug involving Steps moving up & down & retaining content
- [x] Editor UI feedback for first/last items
- [x] Ensure pathway re-arranging is smooth too

### CODE REVIEW

**Comment by EvanLovely** [comment]
@remydenton Not totally done here, but the core bug is taken care of if you want to take a peak at the fix. Also pushing this up now to get a head-start on any CI fixes. More to come.

**Comment by remydenton** [comment]
Thanks @EvanLovely, looking good!

**Comment by EvanLovely** [comment]
@remydenton OK, this is ready for review!

**Comment by remydenton** [comment]
Closing in favor of #1742 for hotfix.

**Pull request closed without merging**
