### PR TITLE
Fix/nav theme colors

### PR DESCRIPTION
**Pull request by WessWillis**
## Jira

https://app.asana.com/0/0/1140762213210489/f

## Summary

Example of currently broken `bolt-theme(`) usage. 

## Details

`bolt-theme` is used with an object argument, as detailed here: https://www.notion.so/basaltinc/bolt-theme-and-bolt-color-979d447ef1914b868703c5b5a8863abc.    Currently it does not work, or there is an issue with this implementation.  

## How to test

Visit /pattern-lab/?p=experiments-micro-journeys  and change the theme to dark.  Note that the  active dot on the lefthand nav always has a white background, regardless of theme.

### CODE REVIEW

**Comment by glassdimly** [comment]
Hi @sghoweri,

Glad to have this conversation with you, and this code has not yet merged, nor is it ready to be merged yet.

This is a workaround for simple color changes that aren't working here:
https://github.com/bolt-design-system/bolt/issues/1437
and 
https://github.com/bolt-design-system/bolt/issues/1443

We have a philosophy about band-aids: they should be easy to put on, and easy to remove.

Workarounds like this are a last resort: this is a backup plan for if we don't get any resolution on those other issues, and it's heavily commented on my current branch with @TODOs.

**Comment by sghoweri** [comment]
@glassdimly totally understood — I just want to make sure this bandaid doesn’t doesn’t get gangrene. 🙂

Here’s a bunch of recommended options I came up with to help get past this + minimize tech debt / mitigate any potential performance overhead.

## Recommended Solutions To Pick From (ranked from most to least ideal)
- Manage everything internally via a new `theme` prop added to the parent + pass the prop down to any immediate children that need to handle internal theme-specific styling.  
    - I’d recommend passing down the property value to the child web component’s via lit-html’s property binding syntax to avoid the need to set HTML attributes. https://lit-html.polymer-project.org/guide/template-reference#binding-types
- Create a generic <bolt-theme> helper component that uses `withContext` to allow children to subscribe to prop changes on the parent
- Switch to only use a single bolt-theme value in our Sass. 
    - Doing this should allow the CSS custom property value to be inherited  like they do everywhere else.
- Switch to use `:host-context(.t-bolt-dark)` as a progressive enhancement in Chrome only.

## Not Recommended
- Disable Shadow DOM entirely
- Use mutation observers to try and figure out what parent theme class has been set recursively (which Shadow DOM could seriously throw off)😬

**Comment by glassdimly** [comment]
@sghoweri,

Understood! Nobody wants gangrene.

What we do want is to be able to meet our deliverables and the asks we get from your team.

I think the first choice here is that we simply fix the issues https://github.com/bolt-design-system/bolt/issues/1443 and https://github.com/bolt-design-system/bolt/issues/1437 so that bolt works as designed and that we have a proper way to escalate blocking issues for our team to you or another senior bolt member.

That is to say, it's not always possible for us to know what your first choice solution to a problem will be without asking. After all, if I'm on a parent component, I'll _still_ need to get the theme from it's `closest` parent, and, what if the theme changes? How will I know? That seems brittle to me. But that's possibly because I don't know every use case of bolt. That is a disadvantage that we overcome by taking with you all. After all, maybe you simply never change the theme after page load. Then `closest` with prop-drilling would work just fine. You know more about how bolt is being used, and we want to learn from your team.

We want to be good citizens of the Pega and Bolt; we want to minimize technical debt; and we want to make performant components. We want to work well in this ecosystem.

We'll learn as we work with you over time, and the longer and deeper we dig into bolt's architecture. And bolt will stabilize over time.

I also think a retainer model, and after the pressure of this deliverable is off, will help us be able to spend time contributing back to bolt. That will help everyone because we'll be actively communicating on PRs and learning from one another more.

**Comment by margoromo** [comment]
Can we update this to reflect our conversation yesterday?

**Comment by glassdimly** [comment]
This PR is closed because theme switching support was implemented in https://github.com/boltdesignsystem/bolt/pull/1454 and the CSS work was cherry-picked there as well.

**Pull request closed without merging**
