### PR TITLE
Academy-related Background Updates

### PR DESCRIPTION
**Pull request by sghoweri**
## Jira
http://vjira2:8080/browse/BDS-1951?filter=-1

## Summary
1st pass at updates to the Background component required for the new Academy homepage comps. 

I'm open to iterating on all of these updates _however_ in the interest of time I'd suggest we don't bikeshed this one 🙂 

Note: this PR requires the `@bolt/core` updates from https://github.com/boltdesignsystem/bolt/pull/1657 in order to compile (already pulled into this branch).

## Details
- Add "full" overlay opacity option
- Add new radial gradient option (`.c-bolt-background__overlay--radial-gradient-fill`)
- "Background Crop" treatment used by academy homepage (living in background at the moment but could end up living elsewhere)
- Also added `.has-transparent-background` class modifier as temp solution for using a dark theme w/o the background color

## How to test
- Review changes

### CODE REVIEW

**Comment by mikemai2awesome** [comment]
Additionally, is there a plan to actually rework the background component and simplify theming so we don't have to keep creating new themes? For example:

```html
<bolt-band theme="light | dark">
  <bolt-background
    color="transparent | indigo | teal | yellow | orange | etc."
    overlay="none | gradient | radial-gradient | solid"
    overlay-opacity="light | medium | heavy | full"
    overlay-blend="color-dodge | color-burn | multiply | etc."
    ></bolt-background>
  Band content. <!-- Theme will determine if content is white on black or vice versa. -->
</bolt-band>
```

If so, adding some `@todo`'s or JIRA tix would be great.

**Comment by sghoweri** [comment]
> Additionally, is there a plan to actually rework the background component and simplify theming so we don't have to keep creating new themes? For example:
> 
> ```
> <bolt-band theme="light | dark">
>   <bolt-background
>     color="transparent | indigo | teal | yellow | orange | etc."
>     overlay="none | gradient | radial-gradient | solid"
>     overlay-opacity="light | medium | heavy | full"
>     overlay-blend="color-dodge | color-burn | multiply | etc."
>     ></bolt-background>
>   Band content. 
> </bolt-band>
> ```
> 
> If so, adding some `@todo`'s or JIRA tix would be great.

If you could help add tix for those to follow up on this that'd be super appreciated

**Comment by sghoweri** [comment]
> There are breakpoint, typography, and spacing changes here. Are they intended for other PRs (core updates)?

Check out the core update first (dependency on this) - should make a lot more sense after that's in!

**Comment by mikemai2awesome** [comment]
> Check out the core update first (dependency on this) - should make a lot more sense after that's in!

The other PR is updated and approved. Let's just make sure this PR doesn't override that one.

**Comment by mikemai2awesome** [comment]
> If you could help add tix for those to follow up on this that'd be super appreciated

@sghoweri JIRA ticket created: http://vjira2:8080/browse/BDS-1972

**Comment by mikemai2awesome** [comment]
@sghoweri Pulled master into this. Should be all set.

**Comment by sghoweri** [comment]
PR was released with v2.15.0

**Pull request merged**
