### PR TITLE
DS-650 PatternLab archive folder

### PR DESCRIPTION
**Pull request by MarcinMr**
## Jira

https://pegadigitalit.atlassian.net/browse/DS-650

## Summary

An archive folder was created

## Details

The following directories were transferred from `50-pages` folder into the new `archive` folder.

- .../05-d8-homepage
- .../10-d8-product-pages
- .../15-d8-resources-details-pages
- .../20-d8-press-and-media
- .../25-d8-agenda-manager
- .../30-d8-partners
- .../35-d8-events
- .../40-d8-content-hub
- .../45-d8-blog
- .../50-d8-careers
- .../55-d8-calculator

## How to test

Pull the branch. 

- Check if all required directories were moved into a new archive folder.
- The Archive folder and Tests folder should be able to toggle with a left nav button.

### CODE REVIEW

**Review by colbytcook — APPROVED** [review]
Approved, I fixed a bug in the code (there was a typo on the archive logic) and moved academy to the archive folder

**Review by mikemai2awesome — CHANGES_REQUESTED** [review]
@MarcinMr @colbytcook Can we do the following?

1. Reduce to just one button: "Show Archive and Test folders".
2. Remove all number prefixes in folder names and file names within Archive, since ordering does not matter anymore.

**Review by danielamorse — APPROVED** [review]
Approved, nice job on the JS. Good to merge once the changes @mikemai2awesome requested are done.

**Comment by MarcinMr** [comment]
> @MarcinMr @colbytcook Can we do the following?
> 
> 1. Reduce to just one button: "Show Archive and Test folders".
> 2. Remove all number prefixes in folder names and file names within Archive, since ordering does not matter anymore.

@mikemai2awesome @colbytcook 

Change requests are done

**Review by mikemai2awesome — CHANGES_REQUESTED** [review]
@MarcinMr The button is not working. It's toggling between Archive and Tests rather than showing/hiding both folders.

**Review by mikemai2awesome — APPROVED** [review]
Tried again in incognito, it works as expected. So it might be just a cache issue.

**Pull request merged**
