### PR TITLE
DS-419: Fix support for Edge 18/44

### PR DESCRIPTION
**Pull request by danielamorse**
## Jira

https://pegadigitalit.atlassian.net/browse/DS-419

## Summary

Fix JS error in Edge 18 that says `Expected '('`.

## Details

I believe this error is thrown because Edge 18 doesn't know how to handle [`...rest` syntax](https://stackoverflow.com/questions/53628191/edge-script1028-expected-identifier-string-or-number). I assume this feature was automatically transpiled before we upgraded Babel, as it does not happen prior to Bolt `3.2.0`.

Explicitly adding `Edge 18` to our browserslist-config fixes the bug in Edge 18 on Browserstack.

I'm also adding `Edge 18` to our Pattern Lab Babel config to fix a JS error on the outer PL page (as opposed to the iframe). You may still notice a JS error on the outer PL page, but at least the page works. I'm not going to go any further to debug PL in Edge 18.

## How to test

- Reviewed deployed site in Edge 18 in Browserstack.
  - [Page](https://hotfix-ds-419-edge-support.boltdesignsystem.com/pattern-lab/?p=components-accordion) in PL
  - [Page](https://hotfix-ds-419-edge-support.boltdesignsystem.com/pattern-lab/patterns/40-components-accordion-05-accordion/40-components-accordion-05-accordion.html) in new tab
- Look at a few demos and verify there is no `Expected '('` error or any other major JS errors.
- @colbytcook please take a look on your real Windows machine with Edge 42/44 if possible to verify the same.

### CODE REVIEW

**Review by cjwhitedev — APPROVED** [review]
Works in Browserstack for me. Checked on Edge 17 like it said in the ticket.

**Comment by danielamorse** [comment]
> Works in Browserstack for me. Checked on Edge 17 like it said in the ticket.

Thanks for reviewing. You mean 18 right? In 17 almost nothing seems to work, at least when I tried.

**Comment by cjwhitedev** [comment]
> > Works in Browserstack for me. Checked on Edge 17 like it said in the ticket.
> 
> Thanks for reviewing. You mean 18 right? In 17 almost nothing seems to work, at least when I tried.

nope, 17. thast what i said in the ticket. i can try 18 though if you want.

**Comment by danielamorse** [comment]
@cjwhitedev ah, ok. I let the original ticket get out of date. See the "How to test" section in the PR for the best testing instructions. You don't have to re-test this one, thanks.

**Review by colbytcook — APPROVED** [review]
Can confirm that on my VMWare Edge 44 instance I am not see this error

**Pull request merged**
